fitur_update/urls.py
from django.conf.urls import url
from .views import index, add_post
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_post', add_post, name='add_post'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import fitur_update.urls as fitur_update

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^fitur-update/', include(fitur_update, namespace='update-status')),
    url(r'^$', RedirectView.as_view(url='fitur-update/', permanent=True), name='$  '),
]

fitur_update/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
	created_date = models.DateTimeField(auto_now_add=True)
	description = models.TextField()

fitur_update/forms.py
from django import forms

class  Status_Form(forms.Form):
	description_attrs = {
		'type': 'text',
		'cols': 50,
		'rows': 4,
		'class': 'status-form-textarea',
		'placeholder':'Apa yang Anda pikirkan?'
	}

	description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

fitur_update/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from .forms import Status_Form
from .models import Status

# Create your views here.
response = {}
def index(request):    
	response['author'] = "Rosa Nur Rizky F.T" #TODO Implement yourname
	status = Status.objects.all()
	response['status'] = status
	response['status_form'] =  Status_Form
	html = 'update_status/update_status.html'
	return render(request, html, response)

def add_post(request):
	form = Status_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['description'] = request.POST['description']
		status = Status(description=response['description'])
		status.save()
		return HttpResponseRedirect('/update-status/')
	else:
		return HttpResponseRedirect('/update-status/')

fitur_update/templates/fitur_update.html
{% extends "fitur_update/layout/base.html" %}

{% block content %}

<section name="input-list" id="input-list">

    <div class="container">
        <form id="form" method="POST" action="{% url 'fitur-update:add_post' %}">
            {% csrf_token %}
            {{ status_form }}
            <div class="post-setting">
                <ul class="sharing-share-box">
                    <li class="upload-image">
                        <div class="button-secondary-small-media">
                            <label class="sharing-share-upload">
                                <span class="svg-icon-wrap"><li-icon aria-hidden="true" type="camera-icon" class="sharing-share-action-media__upload-camera-icon"><svg viewBox="0 0 24 24" width="24px" height="24px" x="0" y="0" preserveAspectRatio="xMinYMin meet" class="artdeco-icon"><g class="large-icon" style="fill: currentColor">
                                    <path d="M21,6H18L16.5,3h-9L6,6H3A1,1,0,0,0,2,7V19a1,1,0,0,0,1,1H21a1,1,0,0,0,1-1V7A1,1,0,0,0,21,6ZM7.36,8l1.5-3h6.28l1.5,3H20v2H16.58a5,5,0,0,0-9.16,0H4V8H7.36Zm7.76,4A3.13,3.13,0,1,1,12,8.88,3.13,3.13,0,0,1,15.13,12ZM4,18V11H7.1a5,5,0,1,0,9.8,0H20v7H4Z"></path>
                                </g></svg></li-icon></span>

                                <span class="sharing-subaction-bar__button-text">
                                  Image
                              </span>
                          </label>
                      </div>
                    </li>
                  <li class="upload-video">
                    <div class="button-secondary-small-media">
                        <label for="uploadElementId" class="sharing-share-action-media__upload-input-label">
                            <span class="svg-icon-wrap"><li-icon aria-hidden="true" type="video-camera-icon" class="sharing-share-action-media__upload-camera-icon"><svg viewBox="0 0 24 24" width="24" height="24" style="" x="0" y="0" preserveAspectRatio="xMinYMin meet"><g class="large-icon" style="fill: currentColor">
                                <path d="M21,5.92a1,1,0,0,0-.57.18L17,8.5V7a1,1,0,0,0-1-1H3A1,1,0,0,0,2,7V17a1,1,0,0,0,1,1H16a1,1,0,0,0,1-1V15.5l3.43,2.4a1,1,0,0,0,.57.18,1,1,0,0,0,1-1V6.92A1,1,0,0,0,21,5.92ZM15,16H4V8H15v8Zm2-5.21,3-2.1v6.62l-3-2.1V10.79Z"></path>
                                </g></svg></li-icon>
                            </span>
                            <span class="sharing-subaction-bar__button-text">Video</span>
                        </label>
                    </div>
                  </li>
              </ul>
              <input id="submit" type="submit" class="button-info" value="Post">
          </div>
          <br>
      </form>
  </div>
</section>

<section name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title"></h2>
        <div class="flex">
            {% if status %}
            {% for data in status %}
            <div class="flex-item">
                <div class="to-do-list">
                    <div class="pembuat">
                        <img src="https://rosatamarindus.github.io/img/profile.jpg" class="image-status">
                        <div class="p-author">
                            <div class="to-do-list-author">
                            {{author}}
                            </div>
                            <br>
                            <div class="to-do-list-date-added">
                            {{data.created_date}}
                            </div>
                        </div>

                    </div>

                    <div class="to-do-list-description">
                        {{data.description}}
                    </div>
                    <div class="to-do-list-delete">
                        <div class="to-do-list-delete-button" data-id="{{data.id}}">Delete</div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Anda belum memposting apapun.
            </div>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}        

fitur_update/templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Lingin">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&amp;lang=en" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;lang=en" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/fitur_update.css' %}" />

    <title>
        {% block title %} Lingin {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "fitur_update/partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "fitur_update/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>

</body>
</html>

fitur_update/templates/partials/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<p> &copy; Made with &hearts; in Depok by {{author}} </p>

fitur_update/templates/partials/header.html
<!-- templates/update_status/partials/header.html -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Ling In</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <!-- LINK MENUJU Status, Profile, Friends, dan Stats  -->
        <li class="nav-item active">
          <a class="nav-link" href="/update-status">Status</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/profile">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/add-friend">Friends</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/statistik">Stats</a>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

fitur_update/templates/update_status/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Lingin">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&amp;lang=en" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;lang=en" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}" />

    <title>
        {% block title %} Lingin {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "update_status/partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "update_status/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>

</body>
</html>

fitur_update/templates/update_status/partials/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<p> &copy; Made with &hearts; in Depok by {{author}} </p>

fitur_update/templates/update_status/partials/header.html
<!-- templates/update_status/partials/header.html -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Ling In</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <!-- LINK MENUJU Status, Profile, Friends, dan Stats  -->
        <li class="nav-item active">
          <a class="nav-link" href="/update-status">Status</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/profile">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/add-friend">Friends</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/statistik">Stats</a>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

fitur_update/templates/update_status/update_status.html
{% extends "update_status/layout/base.html" %}

{% block content %}

<section name="input-list" id="input-list">

    <div class="container">
        <form id="form" method="POST" action="{% url 'update-status:add_post' %}">
            {% csrf_token %}
            {{ status_form }}
            <div class="post-setting">
                <ul class="sharing-share-box">
                    <li class="upload-image">
                        <div class="button-secondary-small-media">
                            <label class="sharing-share-upload">
                                <span class="svg-icon-wrap"><li-icon aria-hidden="true" type="camera-icon" class="sharing-share-action-media__upload-camera-icon"><svg viewBox="0 0 24 24" width="24px" height="24px" x="0" y="0" preserveAspectRatio="xMinYMin meet" class="artdeco-icon"><g class="large-icon" style="fill: currentColor">
                                    <path d="M21,6H18L16.5,3h-9L6,6H3A1,1,0,0,0,2,7V19a1,1,0,0,0,1,1H21a1,1,0,0,0,1-1V7A1,1,0,0,0,21,6ZM7.36,8l1.5-3h6.28l1.5,3H20v2H16.58a5,5,0,0,0-9.16,0H4V8H7.36Zm7.76,4A3.13,3.13,0,1,1,12,8.88,3.13,3.13,0,0,1,15.13,12ZM4,18V11H7.1a5,5,0,1,0,9.8,0H20v7H4Z"></path>
                                </g></svg></li-icon></span>

                                <span class="sharing-subaction-bar__button-text">
                                  Image
                              </span>
                          </label>
                      </div>
                    </li>
                  <li class="upload-video">
                    <div class="button-secondary-small-media">
                        <label for="uploadElementId" class="sharing-share-action-media__upload-input-label">
                            <span class="svg-icon-wrap"><li-icon aria-hidden="true" type="video-camera-icon" class="sharing-share-action-media__upload-camera-icon"><svg viewBox="0 0 24 24" width="24" height="24" style="" x="0" y="0" preserveAspectRatio="xMinYMin meet"><g class="large-icon" style="fill: currentColor">
                                <path d="M21,5.92a1,1,0,0,0-.57.18L17,8.5V7a1,1,0,0,0-1-1H3A1,1,0,0,0,2,7V17a1,1,0,0,0,1,1H16a1,1,0,0,0,1-1V15.5l3.43,2.4a1,1,0,0,0,.57.18,1,1,0,0,0,1-1V6.92A1,1,0,0,0,21,5.92ZM15,16H4V8H15v8Zm2-5.21,3-2.1v6.62l-3-2.1V10.79Z"></path>
                                </g></svg></li-icon>
                            </span>
                            <span class="sharing-subaction-bar__button-text">Video</span>
                        </label>
                    </div>
                  </li>
              </ul>
              <input id="submit" type="submit" class="button-info" value="Post">
          </div>
          <br>
      </form>
  </div>
</section>

<section name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title"></h2>
        <div class="flex">
            {% if status %}
            {% for data in status %}
            <div class="flex-item">
                <div class="to-do-list">
                    <div class="pembuat">
                        <img src="https://rosatamarindus.github.io/img/profile.jpg" class="image-status">
                        <div class="p-author">
                            <div class="to-do-list-author">
                            {{author}}
                            </div>
                            <br>
                            <div class="to-do-list-date-added">
                            {{data.created_date}}
                            </div>
                        </div>

                    </div>

                    <div class="to-do-list-description">
                        {{data.description}}
                    </div>
                    <div class="to-do-list-delete">
                        <div class="to-do-list-delete-button" data-id="{{data.id}}">Delete</div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Anda belum memposting apapun.
            </div>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}        